FROM python:3.10-slim AS base

RUN mkdir /images

WORKDIR /app

COPY requirements.txt .
COPY .env_docker .env
COPY alembic.ini.docker alembic.ini

RUN pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml .

COPY src/ ./src/
RUN pip install -e .

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

RUN alembic upgrade head

EXPOSE 5050
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5050", "wsgi:app"]
