FROM python:3.10-slim AS base

RUN mkdir /images

WORKDIR /app

COPY requirements.txt .
COPY .env_docker .env
COPY alembic.ini.docker alembic.ini

RUN pip install --no-cache-dir -r requirements.txt

COPY pyproject.toml .

COPY src/ ./src/
RUN pip install -e .

RUN apt-get update && \
    apt-get install -y curl postgresql-client && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 5050

# Create entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

CMD ["/docker-entrypoint.sh"]
