services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aiproxysrv
      - POSTGRES_USER=aiproxy
      - POSTGRES_PASSWORD=aiproxy123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webui-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aiproxy -d aiproxysrv"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - webui-net
    command: redis-server --appendonly yes
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 3

  aiproxy-app:
    container_name: aiproxysrv
    restart: unless-stopped
    build: .
    command: /bin/bash -c "alembic -c /app/alembic.ini upgrade head && gunicorn -w 4 -b 0.0.0.0:5050 wsgi:app"
    ports:
      - "5050:5050"
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - DATABASE_URL=postgresql://aiproxy:aiproxy123@postgres:5432/aiproxysrv
      - DEBUG=false
    volumes:
      - .:/app
      - images-data:/images
    networks:
      - webui-net
    links:
      - postgres
      - redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  celery-worker:
    container_name: celery-worker
    restart: unless-stopped
    build: .
    command: celery -A celery_app.celery_config:celery_app worker --loglevel=info --concurrency=1
    user: "1000:1000"
    depends_on:
      - postgres
      - redis
      - aiproxy-app
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/app
    networks:
      - webui-net
volumes:
  postgres-data:
  redis-data:
  images-data:

networks:
  webui-net:
    external: true
    name: webui-network
