services:
  webui:
    image: ghcr.io/open-webui/open-webui:0.6.22
    container_name: ollama-webui
    restart: unless-stopped
    environment:
      # Ollama (lokal)
      - OLLAMA_API_BASE_URL=http://10.0.1.120:11434
      # OpenAI (Dummy – Key später in UI ändern)
      - OPENAI_API_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=DUMMY
    volumes:
      - webui_data:/app/backend/data
    networks:
      - webui-net

  nginx:
    image: nginx:1.23.3
    container_name: webui-proxy
    restart: unless-stopped
    depends_on:
      - webui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/webui.crt:/etc/ssl/certs/webui.crt:ro
      - ./certs/webui.key:/etc/ssl/private/webui.key:ro
    networks:
      - webui-net

volumes:
  webui_data:

networks:
  webui-net:
