FROM nginx:alpine

COPY ./nginx/mime.types /etc/nginx/mime.types
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN "mkdir -p /etc/ssl/certs"
RUN "mkdir -p /usr/share/nginx"

COPY certs/webui.crt /etc/ssl/certs/webui.crt
COPY certs/webui.key /etc/ssl/private/webui.key

COPY ./html /usr/share/nginx/html
