services:
  nginx:
    container_name: forward-proxy
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - webui-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  webui-net:
    external: true
    name: webui-network
