"""Add title and tags to generated_images

Revision ID: 02794a7298bd
Revises: 3cc5ed08a974
Create Date: 2025-09-16 13:19:09.855113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02794a7298bd'
down_revision: Union[str, Sequence[str], None] = '3cc5ed08a974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_images', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('generated_images', sa.Column('tags', sa.Text(), nullable=True))
    op.drop_constraint(op.f('songs_task_id_key'), 'songs', type_='unique')
    op.drop_index(op.f('ix_songs_task_id'), table_name='songs')
    op.create_index(op.f('ix_songs_task_id'), 'songs', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_task_id'), table_name='songs')
    op.create_index(op.f('ix_songs_task_id'), 'songs', ['task_id'], unique=False)
    op.create_unique_constraint(op.f('songs_task_id_key'), 'songs', ['task_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('generated_images', 'tags')
    op.drop_column('generated_images', 'title')
    # ### end Alembic commands ###
