"""Add song_choices table and refactor songs

Revision ID: aaef2a47784e
Revises: 1ab0353590b6
Create Date: 2025-09-12 14:30:35.385583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaef2a47784e'
down_revision: Union[str, Sequence[str], None] = '1ab0353590b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('mureka_choice_id', sa.String(length=255), nullable=True),
    sa.Column('choice_index', sa.Integer(), nullable=True),
    sa.Column('mp3_url', sa.String(length=1000), nullable=True),
    sa.Column('flac_url', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_choices_id'), 'song_choices', ['id'], unique=False)
    op.create_index(op.f('ix_song_choices_song_id'), 'song_choices', ['song_id'], unique=False)
    op.drop_column('songs', 'flac_url')
    op.drop_column('songs', 'image_url')
    op.drop_column('songs', 'title')
    op.drop_column('songs', 'tags')
    op.drop_column('songs', 'video_url')
    op.drop_column('songs', 'duration')
    op.drop_column('songs', 'mp3_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('mp3_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('video_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('tags', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('flac_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_song_choices_song_id'), table_name='song_choices')
    op.drop_index(op.f('ix_song_choices_id'), table_name='song_choices')
    op.drop_table('song_choices')
    # ### end Alembic commands ###
