"""add_rating_to_song_choices

Revision ID: ad849273b893
Revises: 67836ff70afb
Create Date: 2025-09-19 09:56:10.061851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad849273b893'
down_revision: Union[str, Sequence[str], None] = '67836ff70afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song_choices', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song_choices', 'rating')
    # ### end Alembic commands ###
