# Verwende ein Python-Image als Basis 
FROM python:3.13-slim

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die requirements.txt ins Container-Image
COPY ./requirements.txt ./

# Installiere die Abhängigkeiten
RUN pip install --no-cache-dir -r requirements.txt

# CURL installieren
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Kopiere den gesamten Projektinhalt ins Container-Image
COPY . .

# Exponiere den gewünschten Port
EXPOSE 5050

# Starte die Gunicorn-Anwendung
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5050", "dalle3-server:app"]
