# Verwende ein Python-Image als Basis 
FROM python:3.13-slim

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere die requirements.txt und die Python-Skripte ins Container-Image
COPY requirements.txt ./
COPY . .

# Installiere die Abhängigkeiten
RUN pip install --no-cache-dir -r requirements.txt

# Setze Umgebungsvariablen für Flask
ENV FLASK_APP=dalle3-server.py
ENV FLASK_RUN_HOST=0.0.0.0

# Exponiere den gewünschten Port
EXPOSE 5050

# Starte die Flask-Anwendung
CMD ["flask", "run", "--port=5050"]
