FROM python:3.10-slim AS base

WORKDIR /app

# Copy Files
COPY .env .env
COPY src/ ./src/
COPY pyproject.toml .

# Install curl
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Install PIP Dependencies
RUN pip install --no-cache-dir -e .


EXPOSE 5050
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5050", "wsgi:app"]
