services:
  webui:
    image: ghcr.io/open-webui/open-webui:0.6.26
    container_name: ollama-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://10.0.1.120:11434
      - OPENAI_API_BASE_URL=https://api.openai.com/v1
      - OPENAI_API_KEY=DUMMY
      - OLLAMA_KEEP_ALIVE=86400
    volumes:
      - webui_data:/app/backend/data
      - ./data/webui.db:/app/backend/data/webui.db
    networks:
      - webui-net

  nginx:
    image: nginx:1.23.3
    container_name: webui-proxy
    restart: unless-stopped
    depends_on:
      - webui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/webui.crt:/etc/ssl/certs/webui.crt:ro
      - ./certs/webui.key:/etc/ssl/private/webui.key:ro
      - ./logs:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - webui-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/nginx_status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  webui_data:

networks:
  webui-net:
