name: Build and Push Multi-Platform Docker Images

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Manual trigger

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .

      - name: Set up QEMU for multi-platform
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name multiplatform --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build and push aiproxysrv-app
        run: |
          cd aiproxysrv
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --target app \
            -t ${{ env.IMAGE_PREFIX }}/aiproxysrv-app:${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_PREFIX }}/aiproxysrv-app:latest \
            --push \
            .

  build-worker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .

      - name: Set up QEMU for multi-platform
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        run: |
          docker buildx create --name multiplatform --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build and push celery-worker-app
        run: |
          cd aiproxysrv
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --target worker \
            -t ${{ env.IMAGE_PREFIX }}/celery-worker-app:${{ steps.version.outputs.version }} \
            -t ${{ env.IMAGE_PREFIX }}/celery-worker-app:latest \
            --push \
            .
